# Generated by Django 3.2.5 on 2024-01-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0005_email_isdeleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
    ]
