# Generated by Django 3.2.5 on 2023-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('EmailID', models.AutoField(primary_key=True, serialize=False)),
                ('Sender', models.EmailField(max_length=255)),
                ('Reciever', models.EmailField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('ReceivedDate', models.DateTimeField()),
                ('IsPriority', models.IntegerField(default=0)),
            ],
        ),
    ]
