# Generated by Django 3.2.5 on 2023-12-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_email_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='Body',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
