# Generated by Django 3.2.5 on 2024-01-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0004_priorityemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
