# Generated by Django 3.2.5 on 2024-03-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0006_email_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='GmailEmailID',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
