# Generated by Django 3.2.5 on 2023-12-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('EventDescription', models.TextField()),
                ('StartDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndDate', models.DateField()),
                ('EndTime', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
