# Generated by Django 3.2.5 on 2024-02-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='Reminders',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='Time_Estimate',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
