# Generated by Django 3.2.5 on 2024-01-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail_credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
