# Generated by Django 3.2.5 on 2024-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0004_customuser_travelmode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notify_for_Priority_Emails_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_for_ToDoList_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_for_event_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
