# Generated by Django 3.2.5 on 2024-03-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_auto_20240129_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Microsoft_credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
