import imaplib
import base64

class OAuth2IMAP(imaplib.IMAP4_SSL):
    def oauth2_authenticate(self, email_address, access_token):
        auth_string = 'user={}\1auth=Bearer {}\1\1'.format(email_address, access_token)
        auth_string_encoded = base64.b64encode(auth_string.encode('utf-8'))
        self.authenticate('XOAUTH2', lambda x: auth_string_encoded)

# Configuration
EMAIL_ADDRESS = "hamzehhirzalla@outlook.com"
ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJub25jZSI6IjlkYUhJX3ZqU2VicWJsRVp0NlNYVnRvSFVGOHhVT2YtbDBKdG8xTE9XVkUiLCJhbGciOiJSUzI1NiIsIng1dCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSIsImtpZCI6IlhSdmtvOFA3QTNVYVdTblU3Yk05blQwTWpoQSJ9.eyJhdWQiOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsImlzcyI6Imh0dHBzOi8vc3RzLndpbmRvd3MubmV0LzM2ZDdkNDZkLWNiNGMtNGYzMS04NTk2LTc4NDIxNWZkODhkNi8iLCJpYXQiOjE3MDkyNDg4MTksIm5iZiI6MTcwOTI0ODgxOSwiZXhwIjoxNzA5MjU0NDMyLCJhY2N0IjoxLCJhY3IiOiIxIiwiYWlvIjoiQVdRQW0vOFdBQUFBWGRtK01DWEhFR3pDeWVXSDM5ZFgxNEM0K1VRa2RTdVdrVzJzSjA1K3dvbU9kZHR1L2p5b0sweUhsVUdRdkZkdGtqcDZmeXFnSmxwalFENW43WW12ZVBueXJEK1B2R2k0NXB3WXBJdFhuTm1JMWV0WHVXYUFWMU5RT2JqZUg3WUYiLCJhbHRzZWNpZCI6IjE6bGl2ZS5jb206MDAwMzQwMDEzOTIyRjBFRiIsImFtciI6WyJwd2QiXSwiYXBwX2Rpc3BsYXluYW1lIjoic2F0dXJkYXkgYXBwbGljYXRpb24iLCJhcHBpZCI6ImYxNjc1ODhlLTc3OWMtNDYwNC04OTRlLWRjN2FmYWZkMDk1NSIsImFwcGlkYWNyIjoiMSIsImVtYWlsIjoiaGFtemVoaGlyemFsbGFAb3V0bG9vay5jb20iLCJlbmZwb2xpZHMiOltdLCJmYW1pbHlfbmFtZSI6IkhpcnphbGxhIiwiZ2l2ZW5fbmFtZSI6IkhhbXplaCIsImlkcCI6ImxpdmUuY29tIiwiaXBhZGRyIjoiOTIuOTguMTE2Ljg2IiwibG9naW5faGludCI6Ik8uQ2lRd01EQXdNREF3TUMwd01EQXdMVEF3TURBdE56Y3hNeTA1TVRGallUQmpOVGxpWlRrU0pEa3hPRGd3TkRCa0xUWmpOamN0TkdNMVlpMWlNVEV5TFRNMllUTXdOR0kyTm1SaFpCb2FhR0Z0ZW1Wb2FHbHllbUZzYkdGQWIzVjBiRzl2YXk1amIyMGdqUUU9IiwibmFtZSI6ImhhbXplaGhpcnphbGxhIiwib2lkIjoiODUzNzYxMjUtMmJlZC00YTUwLWIyYWYtNjgwMmM1OTQyZTQ0IiwicHVpZCI6IjEwMDMyMDAzNUFEN0IzODciLCJyaCI6IjAuQWE0QWJkVFhOa3pMTVUtRmxuaENGZjJJMWdJQUFBQUFBUEVQemdBQUFBQUFBQUNyQUQ0LiIsInNjcCI6IklNQVAuQWNjZXNzQXNVc2VyLkFsbCIsInNpZCI6ImQ2ZWMwZjhkLWE4YjItNGEzMS04NGMwLWVjZjdiMmUwMTk2MiIsInNpZ25pbl9zdGF0ZSI6WyJrbXNpIl0sInN1YiI6ImxyRHVkWmpOMFd2QzI0eWozTDNFX0RHT1o4YjY0WFVHdUQxV2RwU3FhRnMiLCJ0aWQiOiIzNmQ3ZDQ2ZC1jYjRjLTRmMzEtODU5Ni03ODQyMTVmZDg4ZDYiLCJ1bmlxdWVfbmFtZSI6ImxpdmUuY29tI2hhbXplaGhpcnphbGxhQG91dGxvb2suY29tIiwidXBuIjoiaGFtemVoaGlyemFsbGFfb3V0bG9vay5jb20jRVhUI0Bwcm9qZWN0MzIxdGVzdG91dGxvb2sub25taWNyb3NvZnQuY29tIiwidXRpIjoia1dWN2VpQWNhVS16elhfSW8zY2dBUSIsInZlciI6IjEuMCIsIndpZHMiOlsiMTNiZDFjNzItNmY0YS00ZGNmLTk4NWYtMThkM2I4MGYyMDhhIl19.DdJo3SGaAtBx2ShyzxBm4wpV2sX7WRYA7n_Ja0FjlpxagUDudwSarcj82oML6ykiRfiWnHbPJ9f3uQt3HXMRnYx5yhVzxXvEMd5kwO5z5IOw-j2PdrQctaB8fSjGrExzRF9SOrO_eVYCULOGGHj5EbNc7t27DMUx7EFf5RndwhN1GCA4GUC3yBrcnvoBGOVTdsO-7wPzMvfZ2FUkpPzvTaHjJAolQAjaj15kuUnaZaBPGaquH-OQtsvxzYxCMtdNAPNg2iFZjMWdmHzz-h8MuaT20rlFsWIKbpuP7RVtOsoVPBIB8gPz_mlYqSgovBPb5ro6wHo9bB502Ikz_DOXPQ"
SERVER = "outlook.office365.com"
PORT = 993

try:
    # Initialize IMAP client
    imap_client = OAuth2IMAP(SERVER, PORT)
    imap_client.oauth2_authenticate(EMAIL_ADDRESS, ACCESS_TOKEN)

    # Select the inbox and fetch the last 5 messages (example)
    imap_client.select('inbox')
    typ, data = imap_client.search(None, 'ALL')
    for num in data[0].split()[-5:]:
        typ, msg_data = imap_client.fetch(num, '(RFC822)')
        print('Message %s\n%s\n' % (num, msg_data[0][1]))

    imap_client.close()
    imap_client.logout()
except imaplib.IMAP4.error as e:
    print(f"IMAP4 error: {e}")
