# Generated by Django 3.2.5 on 2024-01-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_event_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Destination',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
