# Generated by Django 3.2.5 on 2023-12-31 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('ToDoID', models.AutoField(primary_key=True, serialize=False)),
                ('Priority', models.IntegerField()),
                ('Due', models.DateTimeField()),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=255)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Time_Estimate', models.DurationField()),
                ('Reminders', models.DateTimeField()),
                ('Status', models.CharField(choices=[('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Complete', 'Complete')], default='Not Started', max_length=50)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
