# Generated by Django 3.2.5 on 2024-02-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0002_auto_20240215_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
